Attempt to fix one frequent flakey executor test
According to the recent two failures `thread 'tests::pallet_executor_unsigned_extrinsics_should_work' panicked at 'The requested execution receipt for block 3 does not exist'`, I subspect the database
writing is not yet finished after waiting an exact number of blocks we
expect, hence we just wait a few more, which won't solve it in 100% but will
probably alleviate the problem to a large extent like what we've done
before.